changelog:
  categories:
    - title: Breaking Changes 💥
      labels:
        - breaking-change
    - title: New Features & Enhancements 🎉
      labels:
        - new-feature
        - enhancement
    - title: Accessibility ♿
      labels:
        - accessibility
    - title: Defects 🐞
      labels:
        - "bug"
    - title: Dependencies 👒 
      labels:
        - dependencies
